using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyLife.Game.Interfaces;
using MyLife.Game.Worlds;

namespace MyLife.Test
{
    [TestClass]
    public class MoveFigures
    {
        [TestMethod]
        public void Glider()
        {
            var initCells = Helpers.Generate(@"
                                               .#.......
                                               ..##.....
                                               .##......
                                               .........
                                               .........
                                               .........
                                               .........");

            var firstGenResult = Helpers.Generate(@"
                                               ..#......
                                               ...#.....
                                               .###.....
                                               .........
                                               .........
                                               .........
                                               .........");

            var secondGenResult = Helpers.Generate(@"
                                               .........
                                               .#.#.....
                                               ..##.....
                                               ..#......
                                               .........
                                               .........
                                               .........");

            var thirdGenResult = Helpers.Generate(@"
                                               .........
                                               ...#.....
                                               .#.#.....
                                               ..##.....
                                               .........
                                               .........
                                               .........");

            var fourthGenResult = Helpers.Generate(@"
                                               .........
                                               ..#......
                                               ...##....
                                               ..##.....
                                               .........
                                               .........
                                               .........");

            var word = new SimpleWorld() as IWorld;
            word.WorldPersistent.Initialize(initCells);
            Helpers.CheckCells(word, initCells);
            Assert.AreEqual(1, word.WorldEvolution.Evolve(), "Wrong number of generation:{0}", word.WorldEvolution.Generation);
            Helpers.CheckCells(word, firstGenResult);
            Assert.AreEqual(2, word.WorldEvolution.Evolve(), "Wrong number of generation:{0}", word.WorldEvolution.Generation);
            Helpers.CheckCells(word, secondGenResult);
            Assert.AreEqual(3, word.WorldEvolution.Evolve(), "Wrong number of generation:{0}", word.WorldEvolution.Generation);
            Helpers.CheckCells(word, thirdGenResult);
            Assert.AreEqual(4, word.WorldEvolution.Evolve(), "Wrong number of generation:{0}", word.WorldEvolution.Generation);
            Helpers.CheckCells(word, fourthGenResult);
        }
    }
}
