using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyLife.Game.Interfaces;
using MyLife.Game.Worlds;

namespace MyLife.Test
{
    [TestClass]
    public class MoveFigures
    {
        [TestMethod]
        public void Glider()
        {
            var initCells = Helpers.Generate(@"
                                               .#.......
                                               ..##.....
                                               .##......
                                               .........
                                               .........
                                               .........
                                               .........");

            var firstGenResult = Helpers.Generate(@"
                                               ..#......
                                               ...#.....
                                               .###.....
                                               .........
                                               .........
                                               .........
                                               .........");

            var secondGenResult = Helpers.Generate(@"
                                               .........
                                               .#.#.....
                                               ..##.....
                                               ..#......
                                               .........
                                               .........
                                               .........");

            var thirdGenResult = Helpers.Generate(@"
                                               .........
                                               ...#.....
                                               .#.#.....
                                               ..##.....
                                               .........
                                               .........
                                               .........");

            var fourthGenResult = Helpers.Generate(@"
                                               .........
                                               ..#......
                                               ...##....
                                               ..##.....
                                               .........
                                               .........
                                               .........");

            var word = new BasicWorld() as IGame;
            var model = new HashModel();
            model.ModelPersistent.Initialize(initCells);
            Helpers.CheckCells(model, initCells);
            Assert.AreEqual(1, word.Evolve(model), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(model, firstGenResult);
            Assert.AreEqual(2, word.Evolve(model), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(model, secondGenResult);
            Assert.AreEqual(3, word.Evolve(model), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(model, thirdGenResult);
            Assert.AreEqual(4, word.Evolve(model), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(model, fourthGenResult);
        }
    }
}
