using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyLife.Game.Interfaces;
using MyLife.Game.Worlds;

namespace MyLife.Test
{
    [TestClass]
    public class SimpleStaticFigures
    {
        [TestMethod]
        public void Beehive()
        {
            var initCells = Helpers.Generate(@"......
                                               ..##..
                                               .#..#.
                                               ..##...");

            var finalCells = Helpers.Generate(@"......
                                               ..##..
                                               .#..#.
                                               ..##...");
            var word = new BasicWorld() as IGame;
            var model = new HashModel();
            model.ModelPersistent.Initialize(initCells);
            Helpers.CheckCells(model, initCells);
            Assert.AreEqual(1, word.Evolve(model), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(model, finalCells);
        }

        [TestMethod]
        public void Loaf()
        {
            var initCells = Helpers.Generate(@".........
                                               .........
                                               ...##....
                                               ..#..#...
                                               ...#.#...
                                               ....#....
                                               .........");

            var finalCells = Helpers.Generate(@".........
                                               .........
                                               ...##....
                                               ..#..#...
                                               ...#.#...
                                               ....#....
                                               .........");
            var word = new BasicWorld() as IGame;
            var model = new HashModel();
            model.ModelPersistent.Initialize(initCells);
            Helpers.CheckCells(model, initCells);
            Assert.AreEqual(1, word.Evolve(model), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(model, finalCells);
        }

        [TestMethod]
        public void Boat()
        {
            var initCells = Helpers.Generate(@".........
                                               .........
                                               .........
                                               ...##....
                                               ...#.#...
                                               ....#....
                                               .........");

            var finalCells = Helpers.Generate(@".........
                                               .........
                                               .........
                                               ...##....
                                               ...#.#...
                                               ....#....
                                               .........");
            var word = new BasicWorld() as IGame;
            var model = new HashModel();
            model.ModelPersistent.Initialize(initCells);
            Helpers.CheckCells(model, initCells);
            Assert.AreEqual(1, word.Evolve(model), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(model, finalCells);
        }

    }
}
