using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyLife.Game;
using MyLife.Game.Worlds;

namespace MyLife.Test
{
    [TestClass]
    public class SimpleStaticFigures
    {
        [TestMethod]
        public void Beehive()
        {
            var initCells = Helpers.Generate(@"......
                                               ..##..
                                               .#..#.
                                               ..##...");

            var finalCells = Helpers.Generate(@"......
                                               ..##..
                                               .#..#.
                                               ..##...");
            var word = new SimpleWorld();
            word.Init(initCells);
            Helpers.CheckCells(word, initCells);
            Assert.AreEqual(1, word.NextGeneration(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, finalCells);
        }

        [TestMethod]
        public void Loaf()
        {
            var initCells = Helpers.Generate(@".........
                                               .........
                                               ...##....
                                               ..#..#...
                                               ...#.#...
                                               ....#....
                                               .........");

            var finalCells = Helpers.Generate(@".........
                                               .........
                                               ...##....
                                               ..#..#...
                                               ...#.#...
                                               ....#....
                                               .........");
            var word = new SimpleWorld();
            word.Init(initCells);
            Helpers.CheckCells(word, initCells);
            Assert.AreEqual(1, word.NextGeneration(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, finalCells);
        }

        [TestMethod]
        public void Boat()
        {
            var initCells = Helpers.Generate(@".........
                                               .........
                                               .........
                                               ...##....
                                               ...#.#...
                                               ....#....
                                               .........");

            var finalCells = Helpers.Generate(@".........
                                               .........
                                               .........
                                               ...##....
                                               ...#.#...
                                               ....#....
                                               ........."); 
            var word = new SimpleWorld();
            word.Init(initCells);
            Helpers.CheckCells(word, initCells);
            Assert.AreEqual(1, word.NextGeneration(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, finalCells);
        }

    }
}
