using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyLife.Game.Interfaces;
using MyLife.Game.Models;

namespace MyLife.Test
{
    [TestClass]
    public class TwoPeriodsFigures
    {
        [TestMethod]
        public void Blinker()
        {
            var initCells = Helpers.Generate(@"
                                               .#.......
                                               .#.......
                                               .#.......
                                               .........
                                               .........
                                               .........
                                               .........");
           
            var firstGenResult = Helpers.Generate(@"
                                               .........
                                               ###......
                                               .........
                                               .........
                                               .........
                                               .........
                                               .........");

            var secondGenResult = Helpers.Generate(@"
                                               .#.......
                                               .#.......
                                               .#.......
                                               .........
                                               .........
                                               .........
                                               .........");

            var word = new BasicWorld(new HashModel()) as IWorld;
            word.Model.ModelPersistent.Initialize(initCells);
            Helpers.CheckCells(word, initCells);
            Assert.AreEqual(1, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, firstGenResult);
            Assert.AreEqual(2, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, secondGenResult);
            Assert.AreEqual(3, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, firstGenResult);
            Assert.AreEqual(4, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, secondGenResult);
        }

        [TestMethod]
        public void Toad()
        {
            var initCells = Helpers.Generate(@"
                                               .........
                                               ...###...
                                               ..###....
                                               .........
                                               .........
                                               .........
                                               .........");

            var firstGenResult = Helpers.Generate(@"
                                               ....#....
                                               ..#..#...
                                               ..#..#...
                                               ...#.....
                                               .........
                                               .........
                                               .........");

            var secondGenResult = Helpers.Generate(@"
                                               .........
                                               ...###...
                                               ..###....
                                               .........
                                               .........
                                               .........
                                               .........");

            var word = new BasicWorld(new HashModel()) as IWorld;
            word.Model.ModelPersistent.Initialize(initCells);
            Helpers.CheckCells(word, initCells);
            Assert.AreEqual(1, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, firstGenResult);
            Assert.AreEqual(2, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, secondGenResult);
            Assert.AreEqual(3, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, firstGenResult);
            Assert.AreEqual(4, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, secondGenResult);
        }

        [TestMethod]
        public void Beacon()
        {
            var initCells = Helpers.Generate(@"
                                               .........
                                               ..##.....
                                               ..#......
                                               .....#...
                                               ....##...
                                               .........
                                               .........");

            var firstGenResult = Helpers.Generate(@"
                                               .........
                                               ..##.....
                                               ..##.....
                                               ....##...
                                               ....##...
                                               .........
                                               .........");

            var secondGenResult = Helpers.Generate(@"
                                               .........
                                               ..##.....
                                               ..#......
                                               .....#...
                                               ....##...
                                               .........
                                               .........");

            var word = new BasicWorld(new HashModel()) as IWorld;
            word.Model.ModelPersistent.Initialize(initCells);
            Helpers.CheckCells(word, initCells);
            Assert.AreEqual(1, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, firstGenResult);
            Assert.AreEqual(2, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, secondGenResult);
            Assert.AreEqual(3, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, firstGenResult);
            Assert.AreEqual(4, word.Evolve(), "Wrong number of generation:{0}", word.Generation);
            Helpers.CheckCells(word, secondGenResult);
        }
    }
}
